### ISSUE TITLE
Failed to load a language-go package grammar

### ISSUE THREAD

**Issue by betawaffle** [atom/language-go#147]
Steps to reproduce:

1. Launch Atom

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [language-go](https://github.com/atom/language-go) package 0.45.0-3

### Stack Trace

Failed to load a language-go package grammar

```
At Grammar missing required scopeName property: /Users/betawaffle/.atom/packages/language-go/grammars/tree-sitter-go.cson in /Users/betawaffle/.atom/packages/language-go/grammars/tree-sitter-go.cson

Error: Grammar missing required scopeName property: /Users/betawaffle/.atom/packages/language-go/grammars/tree-sitter-go.cson
    at /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:128:70
    at /Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:223:65
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
  at /packages/language-go/grammars/tree-sitter-go.cson:1:1
```

### Commands

```
     -0:20.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-dark-fusion-syntax 2.2.1 
atom-ide-ui 0.7.0 
atom-jshint 2.0.0 
busy-signal 1.4.3 
command-logger 0.23.0 
dash 1.7.1 
editor-stats 0.17.0 
environment 1.3.1 
file-icons 2.1.15 
fizzy 0.21.0 
gist-it 0.9.2 
git-difftool 0.2.7 
git-plus 7.10.0 
go-debug 1.5.3 
go-oracle 0.2.1 
go-plus 5.7.1 
go-signature-statusbar 1.2.3 
hydra-syntax-theme 4.0.1 
hyperclick 0.0.0 
intentions 1.1.5 
jshint 1.8.6 
language-assembly 0.7.2 
language-babel 2.81.0 
language-chef 0.11.0 
language-docker 1.1.8 
language-elixir 0.20.3 
language-erlang 3.2.0 
language-graphql 0.9.0 
language-haml 0.25.2 
language-haskell 1.16.2 
language-hcl 0.4.0 
language-javascript-jsx 0.3.7 
language-ledger 0.3.5 
language-lua 0.9.11 
language-nimrod 0.1.0 
language-pascal 0.20.5 
language-pony 0.3.8 
language-protobuf 0.7.1 
language-ragel 0.1.0 
language-rust 0.4.12 
language-salt 0.4.0 
language-systemd 0.1.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-flow 5.6.1 
linter-golinter 1.2.2 
linter-gotype 0.1.0 
linter-govet 0.1.5 
linter-hlint 2.0.0 
linter-rust 0.8.4 
linter-ui-default 1.6.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
monokai 0.24.0 
neutron-syntax 0.7.0 
neutron-ui 0.4.0 
pretty-json 1.6.4 
react 0.17.0 
sort-lines 0.18.0 
source-preview 0.5.3 
teletype 0.4.0 
toggle-quotes 1.1.0 
Zen 0.18.0 
```

**Comment by rsese** [comment]
Thanks for the report!  It looks like you manually installed the `language-go` package at some point which isn't necessary since it's a core package.  Go ahead and run `apm uninstall language-go` and that should fix things for you.
